/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListBusinessRouteImport } from './routes/list-business'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForBusinessRouteImport } from './routes/for-business'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BusinessRegisterRouteImport } from './routes/business.register'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'

const ListBusinessRoute = ListBusinessRouteImport.update({
  id: '/list-business',
  path: '/list-business',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBusinessRoute = ForBusinessRouteImport.update({
  id: '/for-business',
  path: '/for-business',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/business/register',
  path: '/business/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/for-business': typeof ForBusinessRoute
  '/jobs': typeof JobsRoute
  '/list-business': typeof ListBusinessRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/business/register': typeof BusinessRegisterRoute
  '/category/$slug': typeof CategorySlugRoute
  '/events/$id': typeof EventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/for-business': typeof ForBusinessRoute
  '/jobs': typeof JobsRoute
  '/list-business': typeof ListBusinessRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/business/register': typeof BusinessRegisterRoute
  '/category/$slug': typeof CategorySlugRoute
  '/events/$id': typeof EventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/for-business': typeof ForBusinessRoute
  '/jobs': typeof JobsRoute
  '/list-business': typeof ListBusinessRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/business/register': typeof BusinessRegisterRoute
  '/category/$slug': typeof CategorySlugRoute
  '/events/$id': typeof EventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/events'
    | '/explore'
    | '/for-business'
    | '/jobs'
    | '/list-business'
    | '/business/$slug'
    | '/business/register'
    | '/category/$slug'
    | '/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/events'
    | '/explore'
    | '/for-business'
    | '/jobs'
    | '/list-business'
    | '/business/$slug'
    | '/business/register'
    | '/category/$slug'
    | '/events/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/events'
    | '/explore'
    | '/for-business'
    | '/jobs'
    | '/list-business'
    | '/business/$slug'
    | '/business/register'
    | '/category/$slug'
    | '/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ForBusinessRoute: typeof ForBusinessRoute
  JobsRoute: typeof JobsRoute
  ListBusinessRoute: typeof ListBusinessRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  BusinessRegisterRoute: typeof BusinessRegisterRoute
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/list-business': {
      id: '/list-business'
      path: '/list-business'
      fullPath: '/list-business'
      preLoaderRoute: typeof ListBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-business': {
      id: '/for-business'
      path: '/for-business'
      fullPath: '/for-business'
      preLoaderRoute: typeof ForBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/register': {
      id: '/business/register'
      path: '/business/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ForBusinessRoute: ForBusinessRoute,
  JobsRoute: JobsRoute,
  ListBusinessRoute: ListBusinessRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  BusinessRegisterRoute: BusinessRegisterRoute,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
